### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sergiopvilar** [sergiovilar/subtitles-client#1]
- [x] Fix the mess in the Gulp tasks
- [x] Enable subtitles download by clicking in subtitle
- [x] Add support to seasons
- [ ] Manage the subscribed tv shows in the GUI
- [ ] Add support to language management
- [x] Write the extractor for Opensubtitles
